[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
script = "script"

# Solidity compiler settings
solc = "0.8.22"
optimizer = true
optimizer_runs = 200
via_ir = true
evm_version = "cancun"

# Testing and development
gas_reports = ["*"]
ffi = false
fs_permissions = [{ access = "read", path = "./" }]

# Import remappings
remappings = [
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts-upgradeable/lib/openzeppelin-contracts/contracts/",
    "@forge-std/=lib/forge-std/src/",
    "forge-std/=lib/forge-std/src/",
    "@primuslabs/zktls-contracts/=lib/zktls-contracts/"
]

# Fuzz testing
[fuzz]
runs = 1000
max_test_rejects = 65536

# Invariant testing  
[invariant]
runs = 256
depth = 15
fail_on_revert = false
show_metrics = true

# RPC endpoints (can be configured with environment variables)
[rpc_endpoints]
# Add your RPC endpoints here
# sepolia = "${SEPOLIA_RPC_URL}"
# mainnet = "${MAINNET_RPC_URL}"

# Etherscan API keys (for contract verification)
[etherscan]
# Add your Etherscan API keys here
# sepolia = { key = "${ETHERSCAN_API_KEY}" }
# mainnet = { key = "${ETHERSCAN_API_KEY}" }
