// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yjczcyadbrazsqspvpsb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlqY3pjeWFkYnJhenNxc3B2cHNiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyODIxODEsImV4cCI6MjA2Nzg1ODE4MX0.zMXj0eIoWa5YXE1GcB7CWvpxMbuhraGyQOMzkNiRY84";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});